<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>inp</string>
		<string>inc</string>
		<string>incl</string>
	</array>
	<key>name</key>
	<string>Abaqus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#error</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>^(\s)*\*\*.*\n</string>
			<key>name</key>
			<string>comment.line.double-star.abaqus</string>
		</dict>
		<key>error</key>
		<dict>
			<key>comment</key>
			<string>ERROR space between star and keyword</string>
			<key>match</key>
			<string>\*\s+.*</string>
			<key>name</key>
			<string>invalid.illegal.abaqus</string>
		</dict>
		<key>key-value-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.key.abaqus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.assign.abaqus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.value-general.abaqus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\w\-\.]+)(=?)([\w\-\. ]*)</string>
		</dict>
		<key>keyword</key>
		<dict>
			<key>begin</key>
			<string>^\s*(\*)([a-zA-Z0-9\s]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.operator.abaqus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.control.abaqus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(?&lt;!\,|\, |\,  |\,   |\,    |\,     |\,      |\,       |\,        |\,         |\,          |\,           )(\n|$)</string>
			<key>name</key>
			<string>entity.name.section.keyword-lines.abaqus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>begin</key>
			<string>\,</string>
			<key>end</key>
			<string>\b(?= *\,| *$)</string>
			<key>name</key>
			<string>entity.name.section.modifier.abaqus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#key-value-pair</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.abaqus</string>
	<key>uuid</key>
	<string>24f1bc35-ba9c-457b-8f26-db63c6e4bc42</string>
</dict>
</plist>
