<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>inp</string>
		<string>inc</string>
		<string>incl</string>
	</array>
	<key>name</key>
	<string>Abaqus</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comment</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#error</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-general</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keyword-no-option</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#star</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comma</key>
		<dict>
			<key>match</key>
			<string>\,</string>
			<key>name</key>
			<string>punctuation.separator.abaqus</string>
		</dict>
		<key>comment</key>
		<dict>
			<key>match</key>
			<string>^(\s)*\*\*.*\n</string>
			<key>name</key>
			<string>comment.line.double-star.abaqus</string>
		</dict>
		<key>error</key>
		<dict>
			<key>comment</key>
			<string>ERROR space between star and keyword</string>
			<key>match</key>
			<string>(^| \s)\*\s+.*</string>
			<key>name</key>
			<string>invalid.illegal.abaqus</string>
		</dict>
		<key>key-modifier</key>
		<dict>
			<key>match</key>
			<string>(?&lt;=\,)([\.a-zA-Z0-9\s_\-]+)</string>
			<key>name</key>
			<string>entity.name.function.key-general.abaqus</string>
		</dict>
		<key>key-value-pair</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.function.key-general.abaqus</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.assign.abaqus</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.value-general.abaqus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>([\.a-zA-Z0-9\s_\-]+)(=)([\.a-zA-Z0-9 _\-]+)</string>
			<key>name</key>
			<string>entity.name.section.key-value-pair.abaqus</string>
		</dict>
		<key>keyword-general</key>
		<dict>
			<key>begin</key>
			<string>^\s*\*([a-zA-Z0-9\s]+)(?=\,)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.keyword-general.abaqus</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>entity.name.section.keyword-line.abaqus</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#key-value-pair</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#key-modifier</string>
				</dict>
			</array>
		</dict>
		<key>keyword-no-option</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.keyword-no-option.abaqus</string>
				</dict>
			</dict>
			<key>match</key>
			<string>^\s*\*([a-zA-Z0-9\s]+)(?!\,)</string>
			<key>name</key>
			<string>entity.name.section.keyword-line.abaqus</string>
		</dict>
		<key>star</key>
		<dict>
			<key>match</key>
			<string>^\s*\*(?!\*)</string>
			<key>name</key>
			<string>punctuation.definition.star-keyword.abaqus</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>text.abaqus</string>
	<key>uuid</key>
	<string>24f1bc35-ba9c-457b-8f26-db63c6e4bc42</string>
</dict>
</plist>
